volumes:
  redis:
  db-postgres:
  pgadmin-data:


services:
  db:
    image: postgres:15
    container_name: madness_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: madness
      POSTGRES_USER: shawjd
      POSTGRES_PASSWORD: password
    volumes:
      - db-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: dadgad-pg-admin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: JesseShawCodes@gmail.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  redis:
    image: "redis:7.0"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    container_name: dadgad-redis
    ports: 
      - "6379:6379"
    environment:
      TZ: "America/New_York"
    volumes:
      - "redis:/data"
